import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "./context/AuthContext";

export const metadata: Metadata = {
  title: "Game shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&display=swap"
        />
      </head>
      <body>
        <AuthProvider>
          <Header username="" />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
